BEGINNING
Machine Information:
Operating System: Windows 10
PIP List:
Package                      Version                  Editable project location
---------------------------- ------------------------ ------------------------------
absl-py                      1.4.0
accelerate                   0.17.1
addict                       2.4.0
aiohttp                      3.8.4
aiosignal                    1.3.1
alembic                      1.11.1
ansicon                      1.89.0
antlr4-python3-runtime       4.9.3
anyio                        3.6.2
appdirs                      1.4.4
arrow                        1.2.3
asttokens                    2.2.1
astunparse                   1.6.3
async-timeout                4.0.2
attrs                        23.1.0
audioread                    3.0.0
av                           10.0.0
backcall                     0.2.0
basicsr                      1.4.2
beautifulsoup4               4.12.2
blessed                      1.20.0
blobfile                     2.0.2
boltons                      23.0.0
cachetools                   5.3.0
certifi                      2022.12.7
cffi                         1.15.1
charset-normalizer           3.1.0
click                        8.1.3
clip                         1.0
cmaes                        0.9.1
colorama                     0.4.6
coloredlogs                  15.0.1
colorlog                     6.7.0
contourpy                    1.0.7
croniter                     1.3.14
cycler                       0.11.0
dateutils                    0.6.12
decorator                    5.1.1
deepdiff                     6.3.0
deforum                      0.7a0                    c:\users\mix\webui-dev\deforum
diffusers                    0.16.1
einops                       0.6.0
executing                    1.2.0
facexlib                     0.3.0
fastapi                      0.88.0
ffmpeg                       1.4
ffmpeg-python                0.1.7
filelock                     3.12.0
filterpy                     1.4.5
fire                         0.5.0
flatbuffers                  23.3.3
font-roboto                  0.0.1
fonts                        0.0.3
fonttools                    4.39.3
frozenlist                   1.3.3
fsspec                       2023.4.0
ftfy                         6.1.1
future                       0.18.3
fvcore                       0.1.5.post20221221
gast                         0.5.4
gdown                        4.7.1
gfpgan                       1.3.8
gitdb                        4.0.10
GitPython                    3.1.31
google-auth                  2.17.3
google-auth-oauthlib         0.4.6
google-pasta                 0.2.0
greenlet                     2.0.2
grpcio                       1.54.0
h11                          0.14.0
h5py                         3.8.0
huggingface-hub              0.14.1
humanfriendly                10.0
idna                         3.4
imageio                      2.28.1
imageio-ffmpeg               0.4.8
importlib-metadata           6.6.0
inquirer                     3.1.3
iopath                       0.1.10
ipython                      8.12.0
itsdangerous                 2.1.2
jedi                         0.18.2
Jinja2                       3.1.2
jinxed                       1.2.0
joblib                       1.2.0
kandinsky2                   0.0.0
keras                        2.8.0
Keras-Preprocessing          1.1.2
kiwisolver                   1.4.4
kornia                       0.6.0
lark                         1.1.5
lazy_loader                  0.2
libclang                     16.0.0
librosa                      0.10.0.post2
lightning                    2.0.2
lightning-cloud              0.5.36
lightning-utilities          0.8.0
llama-cpp-python             0.1.50
llvmlite                     0.40.0
lmdb                         1.4.1
lxml                         4.9.2
Mako                         1.2.4
Markdown                     3.4.3
markdown-it-py               2.2.0
MarkupSafe                   2.1.2
matplotlib                   3.7.1
matplotlib-inline            0.1.6
mdurl                        0.1.2
mpmath                       1.3.0
msgpack                      1.0.5
multidict                    6.0.4
networkx                     3.1
numba                        0.57.0
numexpr                      2.8.4
numpy                        1.24.2
oauthlib                     3.2.2
olive-ai                     0.2.1
omegaconf                    2.3.0
onnx                         1.14.0
onnxruntime-directml         1.15.0
open-clip-torch              2.16.0
openai                       0.27.6
opencv-contrib-python        4.7.0.72
opencv-python                4.7.0.72
opt-einsum                   3.3.0
optuna                       3.1.1
ordered-set                  4.1.0
packaging                    23.1
pandas                       1.5.3
parso                        0.8.3
pathlib                      1.0.1
pickleshare                  0.7.5
Pillow                       9.5.0
PIMS                         0.6.1
pip                          23.0.1
platformdirs                 3.5.1
pooch                        1.6.0
portalocker                  2.7.0
prompt-toolkit               3.0.38
protobuf                     3.20.3
psutil                       5.9.5
pure-eval                    0.2.2
py3d                         0.0.87
pyasn1                       0.5.0
pyasn1-modules               0.3.0
pycparser                    2.21
pycryptodomex                3.17
pycuda                       2022.2.2
pydantic                     1.10.8
pyDeprecate                  0.3.1
pydispatch                   1.1.0
PyDispatcher                 2.0.7
pyexiv2                      2.8.1
Pygments                     2.15.1
PyJWT                        2.7.0
pyparsing                    3.0.9
pypng                        0.20220715.0
pyqtgraph                    0.12.1
pyreadline3                  3.4.1
PySide6                      6.2.4
PySide6-Addons               6.5.0
PySide6-Essentials           6.5.0
PySocks                      1.7.1
python-dateutil              2.8.2
python-editor                1.0.4
python-multipart             0.0.6
pytools                      2022.1.14
pytorch-lightning            1.4.2
pytz                         2023.3
PyWavelets                   1.4.1
pywin32                      306
PyYAML                       6.0
QtPy                         2.3.1
readchar                     4.0.5
realesrgan                   0.3.0
regex                        2023.5.4
requests                     2.28.2
requests-oauthlib            1.3.1
rich                         13.3.2
rsa                          4.9
safetensors                  0.3.0
scikit-image                 0.20.0
scikit-learn                 1.2.2
scipy                        1.9.1
sentencepiece                0.1.99
setuptools                   67.6.1
shiboken6                    6.2.4
six                          1.16.0
slicerator                   1.1.0
smmap                        5.0.0
sniffio                      1.3.0
soundfile                    0.12.1
soupsieve                    2.4.1
soxr                         0.3.5
SQLAlchemy                   2.0.15
stack-data                   0.6.2
starlette                    0.22.0
starsessions                 1.3.0
sympy                        1.11.1
tabulate                     0.9.0
tb-nightly                   2.12.0a20230126
tensorboard                  2.8.0
tensorboard-data-server      0.6.1
tensorboard-plugin-wit       1.8.1
tensorflow                   2.8.4
tensorflow-estimator         2.8.0
tensorflow-io-gcs-filesystem 0.31.0
tensorrt                     8.6.1
termcolor                    2.3.0
threadpoolctl                3.1.0
tifffile                     2023.4.12
timm                         0.6.13
tokenizers                   0.12.1
tomli                        2.0.1
torch                        2.1.0.dev20230524+cu121
torchaudio                   2.1.0.dev20230524+cu121
torchdiffeq                  0.2.3
torchmetrics                 0.6.0
torchsde                     0.2.5
torchvision                  0.16.0.dev20230525+cu121
tqdm                         4.65.0
traitlets                    5.9.0
trampoline                   0.1.2
transformers                 4.29.2
typing_extensions            4.5.0
urllib3                      1.26.15
uvicorn                      0.22.0
wcwidth                      0.2.6
websocket-client             1.5.2
websockets                   11.0.3
Werkzeug                     2.3.3
wheel                        0.40.0
wrapt                        1.15.0
yacs                         0.1.8
yapf                         0.33.0
yarl                         1.9.2
zipp                         3.15.0
Failed to retrieve envinfo: [WinError 2] The system cannot find the file specified


Timestamp: 2023-05-28 08:47:41
Traceback (most recent call last):
  File "C:\Users\mix\ainodes\ainodes-engine\ldm\modules\diffusionmodules\model.py", line 343, in forward
    try:
NameError: name 'model_management' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\mix\ainodes\ainodes-engine\custom_nodes\ainodes_engine_base_nodes\torch_nodes\ksampler_node.py", line 183, in evalImplementation_thread
    x_sample = self.decode_sample(sample)
  File "C:\Users\mix\ainodes\ainodes-engine\custom_nodes\ainodes_engine_base_nodes\torch_nodes\ksampler_node.py", line 196, in decode_sample
    def decode_sample(self, sample):
  File "C:\Users\mix\.reloadium\package\3.10\reloadium\corium\ll1ll1llll11111lIl1l1\l1l11l1ll1111lllIl1l1.py", line 46, in ll1ll1l1lll1ll1lIl1l1
  File "C:\Users\mix\ainodes\ainodes-engine\custom_nodes\ainodes_engine_base_nodes\torch_nodes\ksampler_node.py", line 197, in decode_sample
    decoded = gs.models["vae"].decode(sample)
  File "C:\Users\mix\ainodes\ainodes-engine\custom_nodes\ainodes_engine_base_nodes\ainodes_backend\model_loader.py", line 398, in decode
    def decode(self, samples):
  File "C:\Users\mix\.reloadium\package\3.10\reloadium\corium\ll1ll1llll11111lIl1l1\l1l11l1ll1111lllIl1l1.py", line 46, in ll1ll1l1lll1ll1lIl1l1
  File "C:\Users\mix\ainodes\ainodes-engine\custom_nodes\ainodes_engine_base_nodes\ainodes_backend\model_loader.py", line 404, in decode
    pixel_samples = self.first_stage_model.decode(1. / self.scale_factor * samples)
  File "C:\Users\mix\ainodes\ainodes-engine\ldm\models\autoencoder.py", line 92, in decode
    def decode(self, z):
  File "C:\Users\mix\.reloadium\package\3.10\reloadium\corium\ll1ll1llll11111lIl1l1\l1l11l1ll1111lllIl1l1.py", line 46, in ll1ll1l1lll1ll1lIl1l1
  File "C:\Users\mix\ainodes\ainodes-engine\ldm\models\autoencoder.py", line 94, in decode
    dec = self.decoder(z)
  File "C:\Users\mix\ainodes\ainodes-engine\nodes_env\lib\site-packages\torch\nn\modules\module.py", line 1502, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "C:\Users\mix\ainodes\ainodes-engine\nodes_env\lib\site-packages\torch\nn\modules\module.py", line 1511, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\mix\ainodes\ainodes-engine\ldm\modules\diffusionmodules\model.py", line 706, in forward
    def forward(self, z):
  File "C:\Users\mix\.reloadium\package\3.10\reloadium\corium\ll1ll1llll11111lIl1l1\l1l11l1ll1111lllIl1l1.py", line 46, in ll1ll1l1lll1ll1lIl1l1
  File "C:\Users\mix\ainodes\ainodes-engine\ldm\modules\diffusionmodules\model.py", line 718, in forward
    h = self.mid.attn_1(h)
  File "C:\Users\mix\ainodes\ainodes-engine\nodes_env\lib\site-packages\torch\nn\modules\module.py", line 1502, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "C:\Users\mix\ainodes\ainodes-engine\nodes_env\lib\site-packages\torch\nn\modules\module.py", line 1511, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\mix\ainodes\ainodes-engine\ldm\modules\diffusionmodules\model.py", line 329, in forward
    def forward(self, x):
  File "C:\Users\mix\.reloadium\package\3.10\reloadium\corium\ll1ll1llll11111lIl1l1\l1l11l1ll1111lllIl1l1.py", line 46, in ll1ll1l1lll1ll1lIl1l1
  File "C:\Users\mix\ainodes\ainodes-engine\ldm\modules\diffusionmodules\model.py", line 346, in forward
    except model_management.OOM_EXCEPTION as e:
NameError: name 'model_management' is not defined

---End of Error---
Timestamp: 2023-05-28 15:16:05
Traceback (most recent call last):
  File "C:\Users\mix\ainodes\ainodes-engine\custom_nodes\ainodes_engine_base_nodes\torch_nodes\ksampler_node.py", line 184, in evalImplementation_thread
    cpu_s = x_sample.cpu()
AttributeError: 'numpy.ndarray' object has no attribute 'cpu'

---End of Error---
Timestamp: 2023-05-28 15:16:14
Traceback (most recent call last):
  File "C:\Users\mix\ainodes\ainodes-engine\custom_nodes\ainodes_engine_base_nodes\torch_nodes\ksampler_node.py", line 184, in evalImplementation_thread
    cpu_s = x_sample.cpu()
AttributeError: 'numpy.ndarray' object has no attribute 'cpu'

---End of Error---
Traceback (most recent call last):
  File "C:\Users\mix\ainodes\ainodes-engine\custom_nodes\ainodes_engine_base_nodes\torch_nodes\ksampler_node.py", line 184, in evalImplementation_thread
    cpu_s = x_sample.cpu()
AttributeError: 'numpy.ndarray' object has no attribute 'cpu'

---End of Error---
Timestamp: 2023-05-28 16:13:40
Traceback (most recent call last):
  File "C:\Users\mix\ainodes\ainodes-engine\ainodes_frontend\base\ai_node_base.py", line 205, in getOutput
    return self.values[object_name]
KeyError: '2282289403104_output_0'

---End of Error---
Timestamp: 2023-05-28 16:13:58
Traceback (most recent call last):
  File "C:\Users\mix\ainodes\ainodes-engine\ainodes_frontend\base\ai_node_base.py", line 205, in getOutput
    return self.values[object_name]
KeyError: '2282289403104_output_0'

---End of Error---
Traceback (most recent call last):
  File "C:\Users\mix\ainodes\ainodes-engine\ainodes_frontend\base\ai_node_base.py", line 205, in getOutput
    return self.values[object_name]
KeyError: '2282289403104_output_0'

---End of Error---
Timestamp: 2023-05-28 16:14:01
Traceback (most recent call last):
  File "C:\Users\mix\ainodes\ainodes-engine\ainodes_frontend\base\ai_node_base.py", line 205, in getOutput
    return self.values[object_name]
KeyError: '2282289403104_output_0'

---End of Error---
Traceback (most recent call last):
  File "C:\Users\mix\ainodes\ainodes-engine\ainodes_frontend\base\ai_node_base.py", line 205, in getOutput
    return self.values[object_name]
KeyError: '2282289403104_output_0'

---End of Error---
Traceback (most recent call last):
  File "C:\Users\mix\ainodes\ainodes-engine\ainodes_frontend\base\ai_node_base.py", line 205, in getOutput
    return self.values[object_name]
KeyError: '2282289403104_output_0'

---End of Error---
Timestamp: 2023-05-28 16:14:04
Traceback (most recent call last):
  File "C:\Users\mix\ainodes\ainodes-engine\ainodes_frontend\base\ai_node_base.py", line 205, in getOutput
    return self.values[object_name]
KeyError: '2282289403104_output_0'

---End of Error---
Traceback (most recent call last):
  File "C:\Users\mix\ainodes\ainodes-engine\ainodes_frontend\base\ai_node_base.py", line 205, in getOutput
    return self.values[object_name]
KeyError: '2282289403104_output_0'

---End of Error---
Traceback (most recent call last):
  File "C:\Users\mix\ainodes\ainodes-engine\ainodes_frontend\base\ai_node_base.py", line 205, in getOutput
    return self.values[object_name]
KeyError: '2282289403104_output_0'

---End of Error---
Traceback (most recent call last):
  File "C:\Users\mix\ainodes\ainodes-engine\ainodes_frontend\base\ai_node_base.py", line 205, in getOutput
    return self.values[object_name]
KeyError: '2282289403104_output_0'

---End of Error---
Timestamp: 2023-05-28 16:14:09
Traceback (most recent call last):
  File "C:\Users\mix\ainodes\ainodes-engine\ainodes_frontend\base\ai_node_base.py", line 205, in getOutput
    return self.values[object_name]
KeyError: '2282289403104_output_0'

---End of Error---
Traceback (most recent call last):
  File "C:\Users\mix\ainodes\ainodes-engine\ainodes_frontend\base\ai_node_base.py", line 205, in getOutput
    return self.values[object_name]
KeyError: '2282289403104_output_0'

---End of Error---
Traceback (most recent call last):
  File "C:\Users\mix\ainodes\ainodes-engine\ainodes_frontend\base\ai_node_base.py", line 205, in getOutput
    return self.values[object_name]
KeyError: '2282289403104_output_0'

---End of Error---
Traceback (most recent call last):
  File "C:\Users\mix\ainodes\ainodes-engine\ainodes_frontend\base\ai_node_base.py", line 205, in getOutput
    return self.values[object_name]
KeyError: '2282289403104_output_0'

---End of Error---
Traceback (most recent call last):
  File "C:\Users\mix\ainodes\ainodes-engine\ainodes_frontend\base\ai_node_base.py", line 205, in getOutput
    return self.values[object_name]
KeyError: '2282289403104_output_0'

---End of Error---
Timestamp: 2023-05-28 16:14:12
Traceback (most recent call last):
  File "C:\Users\mix\ainodes\ainodes-engine\ainodes_frontend\base\ai_node_base.py", line 205, in getOutput
    return self.values[object_name]
KeyError: '2282289403104_output_0'

---End of Error---
Traceback (most recent call last):
  File "C:\Users\mix\ainodes\ainodes-engine\ainodes_frontend\base\ai_node_base.py", line 205, in getOutput
    return self.values[object_name]
KeyError: '2282289403104_output_0'

---End of Error---
Traceback (most recent call last):
  File "C:\Users\mix\ainodes\ainodes-engine\ainodes_frontend\base\ai_node_base.py", line 205, in getOutput
    return self.values[object_name]
KeyError: '2282289403104_output_0'

---End of Error---
Traceback (most recent call last):
  File "C:\Users\mix\ainodes\ainodes-engine\ainodes_frontend\base\ai_node_base.py", line 205, in getOutput
    return self.values[object_name]
KeyError: '2282289403104_output_0'

---End of Error---
Traceback (most recent call last):
  File "C:\Users\mix\ainodes\ainodes-engine\ainodes_frontend\base\ai_node_base.py", line 205, in getOutput
    return self.values[object_name]
KeyError: '2282289403104_output_0'

---End of Error---
Traceback (most recent call last):
  File "C:\Users\mix\ainodes\ainodes-engine\ainodes_frontend\base\ai_node_base.py", line 205, in getOutput
    return self.values[object_name]
KeyError: '2282289403104_output_0'

---End of Error---
Timestamp: 2023-05-28 16:14:15
Traceback (most recent call last):
  File "C:\Users\mix\ainodes\ainodes-engine\ainodes_frontend\base\ai_node_base.py", line 205, in getOutput
    return self.values[object_name]
KeyError: '2282289403104_output_0'

---End of Error---
Traceback (most recent call last):
  File "C:\Users\mix\ainodes\ainodes-engine\ainodes_frontend\base\ai_node_base.py", line 205, in getOutput
    return self.values[object_name]
KeyError: '2282289403104_output_0'

---End of Error---
Traceback (most recent call last):
  File "C:\Users\mix\ainodes\ainodes-engine\ainodes_frontend\base\ai_node_base.py", line 205, in getOutput
    return self.values[object_name]
KeyError: '2282289403104_output_0'

---End of Error---
Traceback (most recent call last):
  File "C:\Users\mix\ainodes\ainodes-engine\ainodes_frontend\base\ai_node_base.py", line 205, in getOutput
    return self.values[object_name]
KeyError: '2282289403104_output_0'

---End of Error---
Traceback (most recent call last):
  File "C:\Users\mix\ainodes\ainodes-engine\ainodes_frontend\base\ai_node_base.py", line 205, in getOutput
    return self.values[object_name]
KeyError: '2282289403104_output_0'

---End of Error---
Traceback (most recent call last):
  File "C:\Users\mix\ainodes\ainodes-engine\ainodes_frontend\base\ai_node_base.py", line 205, in getOutput
    return self.values[object_name]
KeyError: '2282289403104_output_0'

---End of Error---
Traceback (most recent call last):
  File "C:\Users\mix\ainodes\ainodes-engine\ainodes_frontend\base\ai_node_base.py", line 205, in getOutput
    return self.values[object_name]
KeyError: '2282289403104_output_0'

---End of Error---
Timestamp: 2023-05-28 16:14:18
Traceback (most recent call last):
  File "C:\Users\mix\ainodes\ainodes-engine\ainodes_frontend\base\ai_node_base.py", line 205, in getOutput
    return self.values[object_name]
KeyError: '2282289403104_output_0'

---End of Error---
Traceback (most recent call last):
  File "C:\Users\mix\ainodes\ainodes-engine\ainodes_frontend\base\ai_node_base.py", line 205, in getOutput
    return self.values[object_name]
KeyError: '2282289403104_output_0'

---End of Error---
Traceback (most recent call last):
  File "C:\Users\mix\ainodes\ainodes-engine\ainodes_frontend\base\ai_node_base.py", line 205, in getOutput
    return self.values[object_name]
KeyError: '2282289403104_output_0'

---End of Error---
Traceback (most recent call last):
  File "C:\Users\mix\ainodes\ainodes-engine\ainodes_frontend\base\ai_node_base.py", line 205, in getOutput
    return self.values[object_name]
KeyError: '2282289403104_output_0'

---End of Error---
Traceback (most recent call last):
  File "C:\Users\mix\ainodes\ainodes-engine\ainodes_frontend\base\ai_node_base.py", line 205, in getOutput
    return self.values[object_name]
KeyError: '2282289403104_output_0'

---End of Error---
Traceback (most recent call last):
  File "C:\Users\mix\ainodes\ainodes-engine\ainodes_frontend\base\ai_node_base.py", line 205, in getOutput
    return self.values[object_name]
KeyError: '2282289403104_output_0'

---End of Error---
Traceback (most recent call last):
  File "C:\Users\mix\ainodes\ainodes-engine\ainodes_frontend\base\ai_node_base.py", line 205, in getOutput
    return self.values[object_name]
KeyError: '2282289403104_output_0'

---End of Error---
Traceback (most recent call last):
  File "C:\Users\mix\ainodes\ainodes-engine\ainodes_frontend\base\ai_node_base.py", line 205, in getOutput
    return self.values[object_name]
KeyError: '2282289403104_output_0'

---End of Error---
Timestamp: 2023-05-28 17:16:15
Traceback (most recent call last):
  File "C:\Users\mix\ainodes\ainodes-engine\custom_nodes\ainodes_engine_base_nodes\torch_nodes\conditioning_node.py", line 188, in evalImplementation_thread
    result = [self.get_conditioning(prompt=prompt)]
  File "C:\Users\mix\ainodes\ainodes-engine\custom_nodes\ainodes_engine_base_nodes\torch_nodes\conditioning_node.py", line 231, in get_conditioning
    c = clip.encode(prompt)
  File "C:\Users\mix\ainodes\ainodes-engine\custom_nodes\ainodes_engine_base_nodes\ainodes_backend\model_loader.py", line 504, in encode
    raise e
  File "C:\Users\mix\ainodes\ainodes-engine\custom_nodes\ainodes_engine_base_nodes\ainodes_backend\model_loader.py", line 499, in encode
    self.patcher.patch_model()
  File "C:\Users\mix\ainodes\ainodes-engine\custom_nodes\ainodes_engine_base_nodes\ainodes_backend\lora_loader.py", line 150, in patch_model
    w2a = v[3]
IndexError: tuple index out of range

---End of Error---
Timestamp: 2023-05-28 17:16:33
Traceback (most recent call last):
  File "C:\Users\mix\ainodes\ainodes-engine\custom_nodes\ainodes_engine_base_nodes\torch_nodes\conditioning_node.py", line 188, in evalImplementation_thread
    result = [self.get_conditioning(prompt=prompt)]
  File "C:\Users\mix\ainodes\ainodes-engine\custom_nodes\ainodes_engine_base_nodes\torch_nodes\conditioning_node.py", line 231, in get_conditioning
    c = clip.encode(prompt)
  File "C:\Users\mix\ainodes\ainodes-engine\custom_nodes\ainodes_engine_base_nodes\ainodes_backend\model_loader.py", line 504, in encode
    raise e
  File "C:\Users\mix\ainodes\ainodes-engine\custom_nodes\ainodes_engine_base_nodes\ainodes_backend\model_loader.py", line 499, in encode
    self.patcher.patch_model()
  File "C:\Users\mix\ainodes\ainodes-engine\custom_nodes\ainodes_engine_base_nodes\ainodes_backend\lora_loader.py", line 150, in patch_model
    w2a = v[3]
IndexError: tuple index out of range

---End of Error---
Traceback (most recent call last):
  File "C:\Users\mix\ainodes\ainodes-engine\custom_nodes\ainodes_engine_base_nodes\torch_nodes\conditioning_node.py", line 188, in evalImplementation_thread
    result = [self.get_conditioning(prompt=prompt)]
  File "C:\Users\mix\ainodes\ainodes-engine\custom_nodes\ainodes_engine_base_nodes\torch_nodes\conditioning_node.py", line 231, in get_conditioning
    c = clip.encode(prompt)
  File "C:\Users\mix\ainodes\ainodes-engine\custom_nodes\ainodes_engine_base_nodes\ainodes_backend\model_loader.py", line 504, in encode
    raise e
  File "C:\Users\mix\ainodes\ainodes-engine\custom_nodes\ainodes_engine_base_nodes\ainodes_backend\model_loader.py", line 499, in encode
    self.patcher.patch_model()
  File "C:\Users\mix\ainodes\ainodes-engine\custom_nodes\ainodes_engine_base_nodes\ainodes_backend\lora_loader.py", line 150, in patch_model
    w2a = v[3]
IndexError: tuple index out of range

---End of Error---
Timestamp: 2023-05-28 17:16:51
Traceback (most recent call last):
  File "C:\Users\mix\ainodes\ainodes-engine\custom_nodes\ainodes_engine_base_nodes\torch_nodes\conditioning_node.py", line 188, in evalImplementation_thread
    result = [self.get_conditioning(prompt=prompt)]
  File "C:\Users\mix\ainodes\ainodes-engine\custom_nodes\ainodes_engine_base_nodes\torch_nodes\conditioning_node.py", line 231, in get_conditioning
    c = clip.encode(prompt)
  File "C:\Users\mix\ainodes\ainodes-engine\custom_nodes\ainodes_engine_base_nodes\ainodes_backend\model_loader.py", line 504, in encode
    raise e
  File "C:\Users\mix\ainodes\ainodes-engine\custom_nodes\ainodes_engine_base_nodes\ainodes_backend\model_loader.py", line 499, in encode
    self.patcher.patch_model()
  File "C:\Users\mix\ainodes\ainodes-engine\custom_nodes\ainodes_engine_base_nodes\ainodes_backend\lora_loader.py", line 150, in patch_model
    w2a = v[3]
IndexError: tuple index out of range

---End of Error---
Traceback (most recent call last):
  File "C:\Users\mix\ainodes\ainodes-engine\custom_nodes\ainodes_engine_base_nodes\torch_nodes\conditioning_node.py", line 188, in evalImplementation_thread
    result = [self.get_conditioning(prompt=prompt)]
  File "C:\Users\mix\ainodes\ainodes-engine\custom_nodes\ainodes_engine_base_nodes\torch_nodes\conditioning_node.py", line 231, in get_conditioning
    c = clip.encode(prompt)
  File "C:\Users\mix\ainodes\ainodes-engine\custom_nodes\ainodes_engine_base_nodes\ainodes_backend\model_loader.py", line 504, in encode
    raise e
  File "C:\Users\mix\ainodes\ainodes-engine\custom_nodes\ainodes_engine_base_nodes\ainodes_backend\model_loader.py", line 499, in encode
    self.patcher.patch_model()
  File "C:\Users\mix\ainodes\ainodes-engine\custom_nodes\ainodes_engine_base_nodes\ainodes_backend\lora_loader.py", line 150, in patch_model
    w2a = v[3]
IndexError: tuple index out of range

---End of Error---
Traceback (most recent call last):
  File "C:\Users\mix\ainodes\ainodes-engine\custom_nodes\ainodes_engine_base_nodes\torch_nodes\conditioning_node.py", line 188, in evalImplementation_thread
    result = [self.get_conditioning(prompt=prompt)]
  File "C:\Users\mix\ainodes\ainodes-engine\custom_nodes\ainodes_engine_base_nodes\torch_nodes\conditioning_node.py", line 231, in get_conditioning
    c = clip.encode(prompt)
  File "C:\Users\mix\ainodes\ainodes-engine\custom_nodes\ainodes_engine_base_nodes\ainodes_backend\model_loader.py", line 504, in encode
    raise e
  File "C:\Users\mix\ainodes\ainodes-engine\custom_nodes\ainodes_engine_base_nodes\ainodes_backend\model_loader.py", line 499, in encode
    self.patcher.patch_model()
  File "C:\Users\mix\ainodes\ainodes-engine\custom_nodes\ainodes_engine_base_nodes\ainodes_backend\lora_loader.py", line 150, in patch_model
    w2a = v[3]
IndexError: tuple index out of range

---End of Error---
Timestamp: 2023-05-28 17:18:02
Traceback (most recent call last):
  File "C:\Users\mix\ainodes\ainodes-engine\custom_nodes\ainodes_engine_base_nodes\torch_nodes\conditioning_node.py", line 188, in evalImplementation_thread
    result = [self.get_conditioning(prompt=prompt)]
  File "C:\Users\mix\ainodes\ainodes-engine\custom_nodes\ainodes_engine_base_nodes\torch_nodes\conditioning_node.py", line 231, in get_conditioning
    c = clip.encode(prompt)
  File "C:\Users\mix\ainodes\ainodes-engine\custom_nodes\ainodes_engine_base_nodes\ainodes_backend\model_loader.py", line 504, in encode
    raise e
  File "C:\Users\mix\ainodes\ainodes-engine\custom_nodes\ainodes_engine_base_nodes\ainodes_backend\model_loader.py", line 499, in encode
    self.patcher.patch_model()
  File "C:\Users\mix\ainodes\ainodes-engine\custom_nodes\ainodes_engine_base_nodes\ainodes_backend\lora_loader.py", line 150, in patch_model
    w2a = v[3]
IndexError: tuple index out of range

---End of Error---
Traceback (most recent call last):
  File "C:\Users\mix\ainodes\ainodes-engine\custom_nodes\ainodes_engine_base_nodes\torch_nodes\conditioning_node.py", line 188, in evalImplementation_thread
    result = [self.get_conditioning(prompt=prompt)]
  File "C:\Users\mix\ainodes\ainodes-engine\custom_nodes\ainodes_engine_base_nodes\torch_nodes\conditioning_node.py", line 231, in get_conditioning
    c = clip.encode(prompt)
  File "C:\Users\mix\ainodes\ainodes-engine\custom_nodes\ainodes_engine_base_nodes\ainodes_backend\model_loader.py", line 504, in encode
    raise e
  File "C:\Users\mix\ainodes\ainodes-engine\custom_nodes\ainodes_engine_base_nodes\ainodes_backend\model_loader.py", line 499, in encode
    self.patcher.patch_model()
  File "C:\Users\mix\ainodes\ainodes-engine\custom_nodes\ainodes_engine_base_nodes\ainodes_backend\lora_loader.py", line 150, in patch_model
    w2a = v[3]
IndexError: tuple index out of range

---End of Error---
Traceback (most recent call last):
  File "C:\Users\mix\ainodes\ainodes-engine\custom_nodes\ainodes_engine_base_nodes\torch_nodes\conditioning_node.py", line 188, in evalImplementation_thread
    result = [self.get_conditioning(prompt=prompt)]
  File "C:\Users\mix\ainodes\ainodes-engine\custom_nodes\ainodes_engine_base_nodes\torch_nodes\conditioning_node.py", line 231, in get_conditioning
    c = clip.encode(prompt)
  File "C:\Users\mix\ainodes\ainodes-engine\custom_nodes\ainodes_engine_base_nodes\ainodes_backend\model_loader.py", line 504, in encode
    raise e
  File "C:\Users\mix\ainodes\ainodes-engine\custom_nodes\ainodes_engine_base_nodes\ainodes_backend\model_loader.py", line 499, in encode
    self.patcher.patch_model()
  File "C:\Users\mix\ainodes\ainodes-engine\custom_nodes\ainodes_engine_base_nodes\ainodes_backend\lora_loader.py", line 150, in patch_model
    w2a = v[3]
IndexError: tuple index out of range

---End of Error---
Traceback (most recent call last):
  File "C:\Users\mix\ainodes\ainodes-engine\custom_nodes\ainodes_engine_base_nodes\torch_nodes\conditioning_node.py", line 188, in evalImplementation_thread
    result = [self.get_conditioning(prompt=prompt)]
  File "C:\Users\mix\ainodes\ainodes-engine\custom_nodes\ainodes_engine_base_nodes\torch_nodes\conditioning_node.py", line 231, in get_conditioning
    c = clip.encode(prompt)
  File "C:\Users\mix\ainodes\ainodes-engine\custom_nodes\ainodes_engine_base_nodes\ainodes_backend\model_loader.py", line 504, in encode
    raise e
  File "C:\Users\mix\ainodes\ainodes-engine\custom_nodes\ainodes_engine_base_nodes\ainodes_backend\model_loader.py", line 499, in encode
    self.patcher.patch_model()
  File "C:\Users\mix\ainodes\ainodes-engine\custom_nodes\ainodes_engine_base_nodes\ainodes_backend\lora_loader.py", line 150, in patch_model
    w2a = v[3]
IndexError: tuple index out of range

---End of Error---
Timestamp: 2023-05-28 17:19:05
Traceback (most recent call last):
  File "C:\Users\mix\ainodes\ainodes-engine\custom_nodes\ainodes_engine_base_nodes\torch_nodes\conditioning_node.py", line 188, in evalImplementation_thread
    result = [self.get_conditioning(prompt=prompt)]
  File "C:\Users\mix\ainodes\ainodes-engine\custom_nodes\ainodes_engine_base_nodes\torch_nodes\conditioning_node.py", line 231, in get_conditioning
    c = clip.encode(prompt)
  File "C:\Users\mix\ainodes\ainodes-engine\custom_nodes\ainodes_engine_base_nodes\ainodes_backend\model_loader.py", line 504, in encode
    raise e
  File "C:\Users\mix\ainodes\ainodes-engine\custom_nodes\ainodes_engine_base_nodes\ainodes_backend\model_loader.py", line 499, in encode
    self.patcher.patch_model()
  File "C:\Users\mix\ainodes\ainodes-engine\custom_nodes\ainodes_engine_base_nodes\ainodes_backend\lora_loader.py", line 150, in patch_model
    w2a = v[3]
IndexError: tuple index out of range

---End of Error---
Traceback (most recent call last):
  File "C:\Users\mix\ainodes\ainodes-engine\custom_nodes\ainodes_engine_base_nodes\torch_nodes\conditioning_node.py", line 188, in evalImplementation_thread
    result = [self.get_conditioning(prompt=prompt)]
  File "C:\Users\mix\ainodes\ainodes-engine\custom_nodes\ainodes_engine_base_nodes\torch_nodes\conditioning_node.py", line 231, in get_conditioning
    c = clip.encode(prompt)
  File "C:\Users\mix\ainodes\ainodes-engine\custom_nodes\ainodes_engine_base_nodes\ainodes_backend\model_loader.py", line 504, in encode
    raise e
  File "C:\Users\mix\ainodes\ainodes-engine\custom_nodes\ainodes_engine_base_nodes\ainodes_backend\model_loader.py", line 499, in encode
    self.patcher.patch_model()
  File "C:\Users\mix\ainodes\ainodes-engine\custom_nodes\ainodes_engine_base_nodes\ainodes_backend\lora_loader.py", line 150, in patch_model
    w2a = v[3]
IndexError: tuple index out of range

---End of Error---
Traceback (most recent call last):
  File "C:\Users\mix\ainodes\ainodes-engine\custom_nodes\ainodes_engine_base_nodes\torch_nodes\conditioning_node.py", line 188, in evalImplementation_thread
    result = [self.get_conditioning(prompt=prompt)]
  File "C:\Users\mix\ainodes\ainodes-engine\custom_nodes\ainodes_engine_base_nodes\torch_nodes\conditioning_node.py", line 231, in get_conditioning
    c = clip.encode(prompt)
  File "C:\Users\mix\ainodes\ainodes-engine\custom_nodes\ainodes_engine_base_nodes\ainodes_backend\model_loader.py", line 504, in encode
    raise e
  File "C:\Users\mix\ainodes\ainodes-engine\custom_nodes\ainodes_engine_base_nodes\ainodes_backend\model_loader.py", line 499, in encode
    self.patcher.patch_model()
  File "C:\Users\mix\ainodes\ainodes-engine\custom_nodes\ainodes_engine_base_nodes\ainodes_backend\lora_loader.py", line 150, in patch_model
    w2a = v[3]
IndexError: tuple index out of range

---End of Error---
Traceback (most recent call last):
  File "C:\Users\mix\ainodes\ainodes-engine\custom_nodes\ainodes_engine_base_nodes\torch_nodes\conditioning_node.py", line 188, in evalImplementation_thread
    result = [self.get_conditioning(prompt=prompt)]
  File "C:\Users\mix\ainodes\ainodes-engine\custom_nodes\ainodes_engine_base_nodes\torch_nodes\conditioning_node.py", line 231, in get_conditioning
    c = clip.encode(prompt)
  File "C:\Users\mix\ainodes\ainodes-engine\custom_nodes\ainodes_engine_base_nodes\ainodes_backend\model_loader.py", line 504, in encode
    raise e
  File "C:\Users\mix\ainodes\ainodes-engine\custom_nodes\ainodes_engine_base_nodes\ainodes_backend\model_loader.py", line 499, in encode
    self.patcher.patch_model()
  File "C:\Users\mix\ainodes\ainodes-engine\custom_nodes\ainodes_engine_base_nodes\ainodes_backend\lora_loader.py", line 150, in patch_model
    w2a = v[3]
IndexError: tuple index out of range

---End of Error---
Traceback (most recent call last):
  File "C:\Users\mix\ainodes\ainodes-engine\custom_nodes\ainodes_engine_base_nodes\torch_nodes\conditioning_node.py", line 188, in evalImplementation_thread
    result = [self.get_conditioning(prompt=prompt)]
  File "C:\Users\mix\ainodes\ainodes-engine\custom_nodes\ainodes_engine_base_nodes\torch_nodes\conditioning_node.py", line 231, in get_conditioning
    c = clip.encode(prompt)
  File "C:\Users\mix\ainodes\ainodes-engine\custom_nodes\ainodes_engine_base_nodes\ainodes_backend\model_loader.py", line 504, in encode
    raise e
  File "C:\Users\mix\ainodes\ainodes-engine\custom_nodes\ainodes_engine_base_nodes\ainodes_backend\model_loader.py", line 499, in encode
    self.patcher.patch_model()
  File "C:\Users\mix\ainodes\ainodes-engine\custom_nodes\ainodes_engine_base_nodes\ainodes_backend\lora_loader.py", line 150, in patch_model
    w2a = v[3]
IndexError: tuple index out of range

---End of Error---
Timestamp: 2023-05-28 17:19:34
Traceback (most recent call last):
  File "C:\Users\mix\ainodes\ainodes-engine\custom_nodes\ainodes_engine_base_nodes\torch_nodes\conditioning_node.py", line 188, in evalImplementation_thread
    result = [self.get_conditioning(prompt=prompt)]
  File "C:\Users\mix\ainodes\ainodes-engine\custom_nodes\ainodes_engine_base_nodes\torch_nodes\conditioning_node.py", line 231, in get_conditioning
    c = clip.encode(prompt)
  File "C:\Users\mix\ainodes\ainodes-engine\custom_nodes\ainodes_engine_base_nodes\ainodes_backend\model_loader.py", line 504, in encode
    raise e
  File "C:\Users\mix\ainodes\ainodes-engine\custom_nodes\ainodes_engine_base_nodes\ainodes_backend\model_loader.py", line 499, in encode
    self.patcher.patch_model()
  File "C:\Users\mix\ainodes\ainodes-engine\custom_nodes\ainodes_engine_base_nodes\ainodes_backend\lora_loader.py", line 150, in patch_model
    w2a = v[3]
IndexError: tuple index out of range

---End of Error---
Traceback (most recent call last):
  File "C:\Users\mix\ainodes\ainodes-engine\custom_nodes\ainodes_engine_base_nodes\torch_nodes\conditioning_node.py", line 188, in evalImplementation_thread
    result = [self.get_conditioning(prompt=prompt)]
  File "C:\Users\mix\ainodes\ainodes-engine\custom_nodes\ainodes_engine_base_nodes\torch_nodes\conditioning_node.py", line 231, in get_conditioning
    c = clip.encode(prompt)
  File "C:\Users\mix\ainodes\ainodes-engine\custom_nodes\ainodes_engine_base_nodes\ainodes_backend\model_loader.py", line 504, in encode
    raise e
  File "C:\Users\mix\ainodes\ainodes-engine\custom_nodes\ainodes_engine_base_nodes\ainodes_backend\model_loader.py", line 499, in encode
    self.patcher.patch_model()
  File "C:\Users\mix\ainodes\ainodes-engine\custom_nodes\ainodes_engine_base_nodes\ainodes_backend\lora_loader.py", line 150, in patch_model
    w2a = v[3]
IndexError: tuple index out of range

---End of Error---
Traceback (most recent call last):
  File "C:\Users\mix\ainodes\ainodes-engine\custom_nodes\ainodes_engine_base_nodes\torch_nodes\conditioning_node.py", line 188, in evalImplementation_thread
    result = [self.get_conditioning(prompt=prompt)]
  File "C:\Users\mix\ainodes\ainodes-engine\custom_nodes\ainodes_engine_base_nodes\torch_nodes\conditioning_node.py", line 231, in get_conditioning
    c = clip.encode(prompt)
  File "C:\Users\mix\ainodes\ainodes-engine\custom_nodes\ainodes_engine_base_nodes\ainodes_backend\model_loader.py", line 504, in encode
    raise e
  File "C:\Users\mix\ainodes\ainodes-engine\custom_nodes\ainodes_engine_base_nodes\ainodes_backend\model_loader.py", line 499, in encode
    self.patcher.patch_model()
  File "C:\Users\mix\ainodes\ainodes-engine\custom_nodes\ainodes_engine_base_nodes\ainodes_backend\lora_loader.py", line 150, in patch_model
    w2a = v[3]
IndexError: tuple index out of range

---End of Error---
Traceback (most recent call last):
  File "C:\Users\mix\ainodes\ainodes-engine\custom_nodes\ainodes_engine_base_nodes\torch_nodes\conditioning_node.py", line 188, in evalImplementation_thread
    result = [self.get_conditioning(prompt=prompt)]
  File "C:\Users\mix\ainodes\ainodes-engine\custom_nodes\ainodes_engine_base_nodes\torch_nodes\conditioning_node.py", line 231, in get_conditioning
    c = clip.encode(prompt)
  File "C:\Users\mix\ainodes\ainodes-engine\custom_nodes\ainodes_engine_base_nodes\ainodes_backend\model_loader.py", line 504, in encode
    raise e
  File "C:\Users\mix\ainodes\ainodes-engine\custom_nodes\ainodes_engine_base_nodes\ainodes_backend\model_loader.py", line 499, in encode
    self.patcher.patch_model()
  File "C:\Users\mix\ainodes\ainodes-engine\custom_nodes\ainodes_engine_base_nodes\ainodes_backend\lora_loader.py", line 150, in patch_model
    w2a = v[3]
IndexError: tuple index out of range

---End of Error---
Traceback (most recent call last):
  File "C:\Users\mix\ainodes\ainodes-engine\custom_nodes\ainodes_engine_base_nodes\torch_nodes\conditioning_node.py", line 188, in evalImplementation_thread
    result = [self.get_conditioning(prompt=prompt)]
  File "C:\Users\mix\ainodes\ainodes-engine\custom_nodes\ainodes_engine_base_nodes\torch_nodes\conditioning_node.py", line 231, in get_conditioning
    c = clip.encode(prompt)
  File "C:\Users\mix\ainodes\ainodes-engine\custom_nodes\ainodes_engine_base_nodes\ainodes_backend\model_loader.py", line 504, in encode
    raise e
  File "C:\Users\mix\ainodes\ainodes-engine\custom_nodes\ainodes_engine_base_nodes\ainodes_backend\model_loader.py", line 499, in encode
    self.patcher.patch_model()
  File "C:\Users\mix\ainodes\ainodes-engine\custom_nodes\ainodes_engine_base_nodes\ainodes_backend\lora_loader.py", line 150, in patch_model
    w2a = v[3]
IndexError: tuple index out of range

---End of Error---
Traceback (most recent call last):
  File "C:\Users\mix\ainodes\ainodes-engine\custom_nodes\ainodes_engine_base_nodes\torch_nodes\conditioning_node.py", line 188, in evalImplementation_thread
    result = [self.get_conditioning(prompt=prompt)]
  File "C:\Users\mix\ainodes\ainodes-engine\custom_nodes\ainodes_engine_base_nodes\torch_nodes\conditioning_node.py", line 231, in get_conditioning
    c = clip.encode(prompt)
  File "C:\Users\mix\ainodes\ainodes-engine\custom_nodes\ainodes_engine_base_nodes\ainodes_backend\model_loader.py", line 504, in encode
    raise e
  File "C:\Users\mix\ainodes\ainodes-engine\custom_nodes\ainodes_engine_base_nodes\ainodes_backend\model_loader.py", line 499, in encode
    self.patcher.patch_model()
  File "C:\Users\mix\ainodes\ainodes-engine\custom_nodes\ainodes_engine_base_nodes\ainodes_backend\lora_loader.py", line 150, in patch_model
    w2a = v[3]
IndexError: tuple index out of range

---End of Error---
Timestamp: 2023-05-28 17:32:43
Traceback (most recent call last):
  File "C:\Users\mix\ainodes\ainodes-engine\custom_nodes\ainodes_engine_base_nodes\ainodes_backend\model_loader.py", line 501, in encode
    self.patcher.unpatch_model()
  File "C:\Users\mix\ainodes\ainodes-engine\custom_nodes\ainodes_engine_base_nodes\ainodes_backend\lora_loader.py", line 443, in unpatch_model
    model_sd = self.model.state_dict()
TypeError: 'collections.OrderedDict' object is not callable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\mix\ainodes\ainodes-engine\custom_nodes\ainodes_engine_base_nodes\torch_nodes\conditioning_node.py", line 188, in evalImplementation_thread
    result = [self.get_conditioning(prompt=prompt)]
  File "C:\Users\mix\ainodes\ainodes-engine\custom_nodes\ainodes_engine_base_nodes\torch_nodes\conditioning_node.py", line 231, in get_conditioning
    c = clip.encode(prompt)
  File "C:\Users\mix\ainodes\ainodes-engine\custom_nodes\ainodes_engine_base_nodes\ainodes_backend\model_loader.py", line 503, in encode
    self.patcher.unpatch_model()
  File "C:\Users\mix\ainodes\ainodes-engine\custom_nodes\ainodes_engine_base_nodes\ainodes_backend\lora_loader.py", line 443, in unpatch_model
    model_sd = self.model.state_dict()
TypeError: 'collections.OrderedDict' object is not callable

---End of Error---
Timestamp: 2023-05-28 17:38:44
Traceback (most recent call last):
  File "C:\Users\mix\ainodes\ainodes-engine\custom_nodes\ainodes_engine_base_nodes\ainodes_backend\model_loader.py", line 501, in encode
    self.patcher.unpatch_model()
  File "C:\Users\mix\ainodes\ainodes-engine\custom_nodes\ainodes_engine_base_nodes\ainodes_backend\lora_loader.py", line 443, in unpatch_model
    model_sd = self.model.state_dict()
TypeError: 'collections.OrderedDict' object is not callable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\mix\ainodes\ainodes-engine\custom_nodes\ainodes_engine_base_nodes\torch_nodes\conditioning_node.py", line 188, in evalImplementation_thread
    result = [self.get_conditioning(prompt=prompt)]
  File "C:\Users\mix\ainodes\ainodes-engine\custom_nodes\ainodes_engine_base_nodes\torch_nodes\conditioning_node.py", line 231, in get_conditioning
    c = clip.encode(prompt)
  File "C:\Users\mix\ainodes\ainodes-engine\custom_nodes\ainodes_engine_base_nodes\ainodes_backend\model_loader.py", line 503, in encode
    self.patcher.unpatch_model()
  File "C:\Users\mix\ainodes\ainodes-engine\custom_nodes\ainodes_engine_base_nodes\ainodes_backend\lora_loader.py", line 443, in unpatch_model
    model_sd = self.model.state_dict()
TypeError: 'collections.OrderedDict' object is not callable

---End of Error---
Traceback (most recent call last):
  File "C:\Users\mix\ainodes\ainodes-engine\ainodes_frontend\base\ai_node_base.py", line 286, in evalImplementationThreadHandler
    result = self.evalImplementation_thread()
  File "C:\Users\mix\ainodes\ainodes-engine\custom_nodes\ainodes_engine_base_nodes\torch_nodes\lora_loader_node.py", line 100, in evalImplementation_thread
    self.load_lora_to_ckpt(file)
  File "C:\Users\mix\ainodes\ainodes-engine\custom_nodes\ainodes_engine_base_nodes\torch_nodes\lora_loader_node.py", line 128, in load_lora_to_ckpt
    load_lora_for_models(lora_path, strength_model, strength_clip)
TypeError: load_lora_for_models() missing 2 required positional arguments: 'strength_model' and 'strength_clip'

---End of Error---
Timestamp: 2023-05-28 17:38:45
Traceback (most recent call last):
  File "C:\Users\mix\ainodes\ainodes-engine\custom_nodes\ainodes_engine_base_nodes\ainodes_backend\model_loader.py", line 501, in encode
    self.patcher.unpatch_model()
  File "C:\Users\mix\ainodes\ainodes-engine\custom_nodes\ainodes_engine_base_nodes\ainodes_backend\lora_loader.py", line 443, in unpatch_model
    model_sd = self.model.state_dict()
TypeError: 'collections.OrderedDict' object is not callable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\mix\ainodes\ainodes-engine\custom_nodes\ainodes_engine_base_nodes\torch_nodes\conditioning_node.py", line 188, in evalImplementation_thread
    result = [self.get_conditioning(prompt=prompt)]
  File "C:\Users\mix\ainodes\ainodes-engine\custom_nodes\ainodes_engine_base_nodes\torch_nodes\conditioning_node.py", line 231, in get_conditioning
    c = clip.encode(prompt)
  File "C:\Users\mix\ainodes\ainodes-engine\custom_nodes\ainodes_engine_base_nodes\ainodes_backend\model_loader.py", line 503, in encode
    self.patcher.unpatch_model()
  File "C:\Users\mix\ainodes\ainodes-engine\custom_nodes\ainodes_engine_base_nodes\ainodes_backend\lora_loader.py", line 443, in unpatch_model
    model_sd = self.model.state_dict()
TypeError: 'collections.OrderedDict' object is not callable

---End of Error---
Traceback (most recent call last):
  File "C:\Users\mix\ainodes\ainodes-engine\ainodes_frontend\base\ai_node_base.py", line 286, in evalImplementationThreadHandler
    result = self.evalImplementation_thread()
  File "C:\Users\mix\ainodes\ainodes-engine\custom_nodes\ainodes_engine_base_nodes\torch_nodes\lora_loader_node.py", line 100, in evalImplementation_thread
    self.load_lora_to_ckpt(file)
  File "C:\Users\mix\ainodes\ainodes-engine\custom_nodes\ainodes_engine_base_nodes\torch_nodes\lora_loader_node.py", line 128, in load_lora_to_ckpt
    load_lora_for_models(lora_path, strength_model, strength_clip)
TypeError: load_lora_for_models() missing 2 required positional arguments: 'strength_model' and 'strength_clip'

---End of Error---
Traceback (most recent call last):
  File "C:\Users\mix\ainodes\ainodes-engine\custom_nodes\ainodes_engine_base_nodes\ainodes_backend\model_loader.py", line 499, in encode
    self.patcher.patch_model()
  File "C:\Users\mix\ainodes\ainodes-engine\custom_nodes\ainodes_engine_base_nodes\ainodes_backend\lora_loader.py", line 362, in patch_model
    model_sd = self.model.state_dict()
TypeError: 'collections.OrderedDict' object is not callable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\mix\ainodes\ainodes-engine\custom_nodes\ainodes_engine_base_nodes\torch_nodes\conditioning_node.py", line 188, in evalImplementation_thread
    result = [self.get_conditioning(prompt=prompt)]
  File "C:\Users\mix\ainodes\ainodes-engine\custom_nodes\ainodes_engine_base_nodes\torch_nodes\conditioning_node.py", line 231, in get_conditioning
    c = clip.encode(prompt)
  File "C:\Users\mix\ainodes\ainodes-engine\custom_nodes\ainodes_engine_base_nodes\ainodes_backend\model_loader.py", line 503, in encode
    self.patcher.unpatch_model()
  File "C:\Users\mix\ainodes\ainodes-engine\custom_nodes\ainodes_engine_base_nodes\ainodes_backend\lora_loader.py", line 444, in unpatch_model
    model_sd = self.model.state_dict()
TypeError: 'collections.OrderedDict' object is not callable

---End of Error---
Timestamp: 2023-05-28 17:39:19
Traceback (most recent call last):
  File "C:\Users\mix\ainodes\ainodes-engine\ainodes_frontend\base\ai_node_base.py", line 286, in evalImplementationThreadHandler
    result = self.evalImplementation_thread()
  File "C:\Users\mix\ainodes\ainodes-engine\custom_nodes\ainodes_engine_base_nodes\torch_nodes\lora_loader_node.py", line 100, in evalImplementation_thread
    self.load_lora_to_ckpt(file)
  File "C:\Users\mix\ainodes\ainodes-engine\custom_nodes\ainodes_engine_base_nodes\torch_nodes\lora_loader_node.py", line 128, in load_lora_to_ckpt
    load_lora_for_models(lora_path, strength_model, strength_clip)
TypeError: load_lora_for_models() missing 2 required positional arguments: 'strength_model' and 'strength_clip'

---End of Error---
Timestamp: 2023-05-28 17:39:51
Traceback (most recent call last):
  File "C:\Users\mix\ainodes\ainodes-engine\ainodes_frontend\base\ai_node_base.py", line 286, in evalImplementationThreadHandler
    result = self.evalImplementation_thread()
  File "C:\Users\mix\ainodes\ainodes-engine\custom_nodes\ainodes_engine_base_nodes\torch_nodes\lora_loader_node.py", line 100, in evalImplementation_thread
    self.load_lora_to_ckpt(file)
  File "C:\Users\mix\ainodes\ainodes-engine\custom_nodes\ainodes_engine_base_nodes\torch_nodes\lora_loader_node.py", line 128, in load_lora_to_ckpt
    load_lora_for_models(lora_path, strength_model, strength_clip)
TypeError: load_lora_for_models() missing 2 required positional arguments: 'strength_model' and 'strength_clip'

---End of Error---
Traceback (most recent call last):
  File "C:\Users\mix\ainodes\ainodes-engine\ainodes_frontend\base\ai_node_base.py", line 286, in evalImplementationThreadHandler
    result = self.evalImplementation_thread()
  File "C:\Users\mix\ainodes\ainodes-engine\custom_nodes\ainodes_engine_base_nodes\torch_nodes\lora_loader_node.py", line 100, in evalImplementation_thread
    self.load_lora_to_ckpt(file)
  File "C:\Users\mix\ainodes\ainodes-engine\custom_nodes\ainodes_engine_base_nodes\torch_nodes\lora_loader_node.py", line 128, in load_lora_to_ckpt
    load_lora_for_models(lora_path, strength_model, strength_clip)
TypeError: load_lora_for_models() missing 2 required positional arguments: 'strength_model' and 'strength_clip'

---End of Error---
Timestamp: 2023-05-28 17:46:20
Traceback (most recent call last):
  File "C:\Users\mix\ainodes\ainodes-engine\custom_nodes\ainodes_engine_base_nodes\torch_nodes\ksampler_node.py", line 163, in evalImplementation_thread
    sample = common_ksampler(device="cuda",
  File "C:\Users\mix\ainodes\ainodes-engine\custom_nodes\ainodes_engine_base_nodes\ainodes_backend\k_sampler.py", line 71, in common_ksampler
    samples = sampler.sample(noise, positive_copy, negative_copy, cfg=cfg, latent_image=latent_image, start_step=start_step, last_step=last_step, force_full_denoise=force_full_denoise, denoise_mask=noise_mask, callback=callback, model_key=model_key)
  File "C:\Users\mix\ainodes\ainodes-engine\custom_nodes\ainodes_engine_base_nodes\ainodes_backend\samplers.py", line 624, in sample
    samples = getattr(k_diffusion_sampling, "sample_{}".format(self.sampler))(self.model_k, noise, sigmas, extra_args=extra_args, callback=callback)
  File "C:\Users\mix\ainodes\ainodes-engine\nodes_env\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "C:\Users\mix\ainodes\ainodes-engine\custom_nodes\ainodes_engine_base_nodes\ainodes_backend\k_diffusion\sampling.py", line 128, in sample_euler
    denoised = model(x, sigma_hat * s_in, **extra_args)
  File "C:\Users\mix\ainodes\ainodes-engine\nodes_env\lib\site-packages\torch\nn\modules\module.py", line 1502, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "C:\Users\mix\ainodes\ainodes-engine\nodes_env\lib\site-packages\torch\nn\modules\module.py", line 1511, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\mix\ainodes\ainodes-engine\custom_nodes\ainodes_engine_base_nodes\ainodes_backend\samplers.py", line 362, in forward
    out = self.inner_model(x, sigma, cond=cond, uncond=uncond, cond_scale=cond_scale, cond_concat=cond_concat, model_options=model_options)
  File "C:\Users\mix\ainodes\ainodes-engine\nodes_env\lib\site-packages\torch\nn\modules\module.py", line 1502, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "C:\Users\mix\ainodes\ainodes-engine\nodes_env\lib\site-packages\torch\nn\modules\module.py", line 1511, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\mix\ainodes\ainodes-engine\custom_nodes\ainodes_engine_base_nodes\ainodes_backend\k_diffusion\external.py", line 169, in forward
    return self.get_v(input * c_in, self.sigma_to_t(sigma), **kwargs) * c_out + input * c_skip
  File "C:\Users\mix\ainodes\ainodes-engine\custom_nodes\ainodes_engine_base_nodes\ainodes_backend\samplers.py", line 342, in get_v
    return self.inner_model.apply_model(x, t, cond, **kwargs)
  File "C:\Users\mix\ainodes\ainodes-engine\custom_nodes\ainodes_engine_base_nodes\ainodes_backend\samplers.py", line 351, in apply_model
    out = sampling_function(self.inner_model.apply_model, x, timestep, uncond, cond, cond_scale, cond_concat, model_options=model_options)
  File "C:\Users\mix\ainodes\ainodes-engine\custom_nodes\ainodes_engine_base_nodes\ainodes_backend\samplers.py", line 330, in sampling_function
    cond, uncond = calc_cond_uncond_batch(model_function, cond, uncond, x, timestep, max_total_area, cond_concat, model_options)
  File "C:\Users\mix\ainodes\ainodes-engine\custom_nodes\ainodes_engine_base_nodes\ainodes_backend\samplers.py", line 307, in calc_cond_uncond_batch
    output = model_function(input_x, timestep_, cond=c).chunk(batch_chunks)
  File "C:\Users\mix\ainodes\ainodes-engine\custom_nodes\ainodes_engine_base_nodes\ainodes_backend\sd_optimizations\sd_hijack_unet.py", line 71, in <lambda>
    setattr(resolved_obj, func_path[-1], lambda *args, **kwargs: self(*args, **kwargs))
  File "C:\Users\mix\ainodes\ainodes-engine\custom_nodes\ainodes_engine_base_nodes\ainodes_backend\sd_optimizations\sd_hijack_unet.py", line 82, in __call__
    return self.__orig_func(*args, **kwargs)
  File "C:\Users\mix\ainodes\ainodes-engine\ldm\models\diffusion\ddpm.py", line 859, in apply_model
    x_recon = self.model(x_noisy, t, **cond)
  File "C:\Users\mix\ainodes\ainodes-engine\nodes_env\lib\site-packages\torch\nn\modules\module.py", line 1502, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "C:\Users\mix\ainodes\ainodes-engine\nodes_env\lib\site-packages\torch\nn\modules\module.py", line 1511, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\mix\ainodes\ainodes-engine\ldm\models\diffusion\ddpm.py", line 1337, in forward
    out = self.diffusion_model(x, t, context=cc, control=control, transformer_options=transformer_options)
  File "C:\Users\mix\ainodes\ainodes-engine\nodes_env\lib\site-packages\torch\nn\modules\module.py", line 1502, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "C:\Users\mix\ainodes\ainodes-engine\nodes_env\lib\site-packages\torch\nn\modules\module.py", line 1511, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\mix\ainodes\ainodes-engine\ldm\modules\diffusionmodules\openaimodel.py", line 821, in forward
    h = forward_timestep_embed(module, h, emb, context, transformer_options)
  File "C:\Users\mix\ainodes\ainodes-engine\ldm\modules\diffusionmodules\openaimodel.py", line 97, in forward_timestep_embed
    x = layer(x, context, transformer_options)
  File "C:\Users\mix\ainodes\ainodes-engine\nodes_env\lib\site-packages\torch\nn\modules\module.py", line 1502, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "C:\Users\mix\ainodes\ainodes-engine\nodes_env\lib\site-packages\torch\nn\modules\module.py", line 1511, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\mix\ainodes\ainodes-engine\ldm\modules\attention.py", line 637, in forward
    x = block(x, context=context[i], transformer_options=transformer_options)
  File "C:\Users\mix\ainodes\ainodes-engine\nodes_env\lib\site-packages\torch\nn\modules\module.py", line 1502, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "C:\Users\mix\ainodes\ainodes-engine\nodes_env\lib\site-packages\torch\nn\modules\module.py", line 1511, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\mix\ainodes\ainodes-engine\ldm\modules\attention.py", line 526, in forward
    return checkpoint(self._forward, (x, context, transformer_options), self.parameters(), self.checkpoint)
  File "C:\Users\mix\ainodes\ainodes-engine\ldm\modules\diffusionmodules\util.py", line 121, in checkpoint
    return CheckpointFunction.apply(func, len(inputs), *args)
  File "C:\Users\mix\ainodes\ainodes-engine\nodes_env\lib\site-packages\torch\autograd\function.py", line 506, in apply
    return super().apply(*args, **kwargs)  # type: ignore[misc]
  File "C:\Users\mix\ainodes\ainodes-engine\ldm\modules\diffusionmodules\util.py", line 136, in forward
    output_tensors = ctx.run_function(*ctx.input_tensors)
  File "C:\Users\mix\ainodes\ainodes-engine\ldm\modules\attention.py", line 556, in _forward
    n = self.attn1(n, context=context_attn1, value=value_attn1)
  File "C:\Users\mix\ainodes\ainodes-engine\nodes_env\lib\site-packages\torch\nn\modules\module.py", line 1502, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "C:\Users\mix\ainodes\ainodes-engine\nodes_env\lib\site-packages\torch\nn\modules\module.py", line 1511, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\mix\ainodes\ainodes-engine\ldm\modules\attention.py", line 381, in forward
    sim = einsum('b i d, b j d -> b i j', q, k) * self.scale
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 18.91 GiB. GPU 0 has a total capacty of 23.99 GiB of which 727.41 MiB is free. Of the allocated memory 21.14 GiB is allocated by PyTorch, and 121.08 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

---End of Error---
Timestamp: 2023-05-28 17:46:50
Traceback (most recent call last):
  File "C:\Users\mix\ainodes\ainodes-engine\custom_nodes\ainodes_engine_base_nodes\torch_nodes\ksampler_node.py", line 163, in evalImplementation_thread
    sample = common_ksampler(device="cuda",
  File "C:\Users\mix\ainodes\ainodes-engine\custom_nodes\ainodes_engine_base_nodes\ainodes_backend\k_sampler.py", line 71, in common_ksampler
    samples = sampler.sample(noise, positive_copy, negative_copy, cfg=cfg, latent_image=latent_image, start_step=start_step, last_step=last_step, force_full_denoise=force_full_denoise, denoise_mask=noise_mask, callback=callback, model_key=model_key)
  File "C:\Users\mix\ainodes\ainodes-engine\custom_nodes\ainodes_engine_base_nodes\ainodes_backend\samplers.py", line 624, in sample
    samples = getattr(k_diffusion_sampling, "sample_{}".format(self.sampler))(self.model_k, noise, sigmas, extra_args=extra_args, callback=callback)
  File "C:\Users\mix\ainodes\ainodes-engine\nodes_env\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "C:\Users\mix\ainodes\ainodes-engine\custom_nodes\ainodes_engine_base_nodes\ainodes_backend\k_diffusion\sampling.py", line 128, in sample_euler
    denoised = model(x, sigma_hat * s_in, **extra_args)
  File "C:\Users\mix\ainodes\ainodes-engine\nodes_env\lib\site-packages\torch\nn\modules\module.py", line 1502, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "C:\Users\mix\ainodes\ainodes-engine\nodes_env\lib\site-packages\torch\nn\modules\module.py", line 1511, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\mix\ainodes\ainodes-engine\custom_nodes\ainodes_engine_base_nodes\ainodes_backend\samplers.py", line 362, in forward
    out = self.inner_model(x, sigma, cond=cond, uncond=uncond, cond_scale=cond_scale, cond_concat=cond_concat, model_options=model_options)
  File "C:\Users\mix\ainodes\ainodes-engine\nodes_env\lib\site-packages\torch\nn\modules\module.py", line 1502, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "C:\Users\mix\ainodes\ainodes-engine\nodes_env\lib\site-packages\torch\nn\modules\module.py", line 1511, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\mix\ainodes\ainodes-engine\custom_nodes\ainodes_engine_base_nodes\ainodes_backend\k_diffusion\external.py", line 169, in forward
    return self.get_v(input * c_in, self.sigma_to_t(sigma), **kwargs) * c_out + input * c_skip
  File "C:\Users\mix\ainodes\ainodes-engine\custom_nodes\ainodes_engine_base_nodes\ainodes_backend\samplers.py", line 342, in get_v
    return self.inner_model.apply_model(x, t, cond, **kwargs)
  File "C:\Users\mix\ainodes\ainodes-engine\custom_nodes\ainodes_engine_base_nodes\ainodes_backend\samplers.py", line 351, in apply_model
    out = sampling_function(self.inner_model.apply_model, x, timestep, uncond, cond, cond_scale, cond_concat, model_options=model_options)
  File "C:\Users\mix\ainodes\ainodes-engine\custom_nodes\ainodes_engine_base_nodes\ainodes_backend\samplers.py", line 330, in sampling_function
    cond, uncond = calc_cond_uncond_batch(model_function, cond, uncond, x, timestep, max_total_area, cond_concat, model_options)
  File "C:\Users\mix\ainodes\ainodes-engine\custom_nodes\ainodes_engine_base_nodes\ainodes_backend\samplers.py", line 307, in calc_cond_uncond_batch
    output = model_function(input_x, timestep_, cond=c).chunk(batch_chunks)
  File "C:\Users\mix\ainodes\ainodes-engine\custom_nodes\ainodes_engine_base_nodes\ainodes_backend\sd_optimizations\sd_hijack_unet.py", line 71, in <lambda>
    setattr(resolved_obj, func_path[-1], lambda *args, **kwargs: self(*args, **kwargs))
  File "C:\Users\mix\ainodes\ainodes-engine\custom_nodes\ainodes_engine_base_nodes\ainodes_backend\sd_optimizations\sd_hijack_unet.py", line 82, in __call__
    return self.__orig_func(*args, **kwargs)
  File "C:\Users\mix\ainodes\ainodes-engine\ldm\models\diffusion\ddpm.py", line 859, in apply_model
    x_recon = self.model(x_noisy, t, **cond)
  File "C:\Users\mix\ainodes\ainodes-engine\nodes_env\lib\site-packages\torch\nn\modules\module.py", line 1502, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "C:\Users\mix\ainodes\ainodes-engine\nodes_env\lib\site-packages\torch\nn\modules\module.py", line 1511, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\mix\ainodes\ainodes-engine\ldm\models\diffusion\ddpm.py", line 1337, in forward
    out = self.diffusion_model(x, t, context=cc, control=control, transformer_options=transformer_options)
  File "C:\Users\mix\ainodes\ainodes-engine\nodes_env\lib\site-packages\torch\nn\modules\module.py", line 1502, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "C:\Users\mix\ainodes\ainodes-engine\nodes_env\lib\site-packages\torch\nn\modules\module.py", line 1511, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\mix\ainodes\ainodes-engine\ldm\modules\diffusionmodules\openaimodel.py", line 821, in forward
    h = forward_timestep_embed(module, h, emb, context, transformer_options)
  File "C:\Users\mix\ainodes\ainodes-engine\ldm\modules\diffusionmodules\openaimodel.py", line 97, in forward_timestep_embed
    x = layer(x, context, transformer_options)
  File "C:\Users\mix\ainodes\ainodes-engine\nodes_env\lib\site-packages\torch\nn\modules\module.py", line 1502, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "C:\Users\mix\ainodes\ainodes-engine\nodes_env\lib\site-packages\torch\nn\modules\module.py", line 1511, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\mix\ainodes\ainodes-engine\ldm\modules\attention.py", line 637, in forward
    x = block(x, context=context[i], transformer_options=transformer_options)
  File "C:\Users\mix\ainodes\ainodes-engine\nodes_env\lib\site-packages\torch\nn\modules\module.py", line 1502, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "C:\Users\mix\ainodes\ainodes-engine\nodes_env\lib\site-packages\torch\nn\modules\module.py", line 1511, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\mix\ainodes\ainodes-engine\ldm\modules\attention.py", line 526, in forward
    return checkpoint(self._forward, (x, context, transformer_options), self.parameters(), self.checkpoint)
  File "C:\Users\mix\ainodes\ainodes-engine\ldm\modules\diffusionmodules\util.py", line 121, in checkpoint
    return CheckpointFunction.apply(func, len(inputs), *args)
  File "C:\Users\mix\ainodes\ainodes-engine\nodes_env\lib\site-packages\torch\autograd\function.py", line 506, in apply
    return super().apply(*args, **kwargs)  # type: ignore[misc]
  File "C:\Users\mix\ainodes\ainodes-engine\ldm\modules\diffusionmodules\util.py", line 136, in forward
    output_tensors = ctx.run_function(*ctx.input_tensors)
  File "C:\Users\mix\ainodes\ainodes-engine\ldm\modules\attention.py", line 556, in _forward
    n = self.attn1(n, context=context_attn1, value=value_attn1)
  File "C:\Users\mix\ainodes\ainodes-engine\nodes_env\lib\site-packages\torch\nn\modules\module.py", line 1502, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "C:\Users\mix\ainodes\ainodes-engine\nodes_env\lib\site-packages\torch\nn\modules\module.py", line 1511, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\mix\ainodes\ainodes-engine\ldm\modules\attention.py", line 381, in forward
    sim = einsum('b i d, b j d -> b i j', q, k) * self.scale
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 18.91 GiB. GPU 0 has a total capacty of 23.99 GiB of which 727.41 MiB is free. Of the allocated memory 21.14 GiB is allocated by PyTorch, and 121.08 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

---End of Error---
Traceback (most recent call last):
  File "C:\Users\mix\ainodes\ainodes-engine\custom_nodes\ainodes_engine_base_nodes\torch_nodes\ksampler_node.py", line 184, in evalImplementation_thread
    x_sample = self.decode_sample(sample)
  File "C:\Users\mix\ainodes\ainodes-engine\custom_nodes\ainodes_engine_base_nodes\torch_nodes\ksampler_node.py", line 198, in decode_sample
    decoded = gs.models["vae"].decode(sample)
  File "C:\Users\mix\ainodes\ainodes-engine\custom_nodes\ainodes_engine_base_nodes\ainodes_backend\model_loader.py", line 404, in decode
    pixel_samples = self.first_stage_model.decode(1. / self.scale_factor * samples)
  File "C:\Users\mix\ainodes\ainodes-engine\ldm\models\autoencoder.py", line 94, in decode
    dec = self.decoder(z)
  File "C:\Users\mix\ainodes\ainodes-engine\nodes_env\lib\site-packages\torch\nn\modules\module.py", line 1502, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "C:\Users\mix\ainodes\ainodes-engine\nodes_env\lib\site-packages\torch\nn\modules\module.py", line 1511, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\mix\ainodes\ainodes-engine\ldm\modules\diffusionmodules\model.py", line 724, in forward
    h = self.up[i_level].block[i_block](h, temb)
  File "C:\Users\mix\ainodes\ainodes-engine\nodes_env\lib\site-packages\torch\nn\modules\module.py", line 1502, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "C:\Users\mix\ainodes\ainodes-engine\nodes_env\lib\site-packages\torch\nn\modules\module.py", line 1511, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\mix\ainodes\ainodes-engine\ldm\modules\diffusionmodules\model.py", line 133, in forward
    h = self.conv1(h)
  File "C:\Users\mix\ainodes\ainodes-engine\nodes_env\lib\site-packages\torch\nn\modules\module.py", line 1502, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "C:\Users\mix\ainodes\ainodes-engine\nodes_env\lib\site-packages\torch\nn\modules\module.py", line 1511, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\mix\ainodes\ainodes-engine\nodes_env\lib\site-packages\torch\nn\modules\conv.py", line 463, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "C:\Users\mix\ainodes\ainodes-engine\nodes_env\lib\site-packages\torch\nn\modules\conv.py", line 459, in _conv_forward
    return F.conv2d(input, weight, bias, self.stride,
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 704.00 MiB. GPU 0 has a total capacty of 23.99 GiB of which 0 bytes is free. Of the allocated memory 22.06 GiB is allocated by PyTorch, and 346.75 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

---End of Error---
Timestamp: 2023-05-28 17:48:37
Traceback (most recent call last):
  File "C:\Users\mix\ainodes\ainodes-engine\custom_nodes\ainodes_engine_base_nodes\torch_nodes\ksampler_node.py", line 163, in evalImplementation_thread
    sample = common_ksampler(device="cuda",
  File "C:\Users\mix\ainodes\ainodes-engine\custom_nodes\ainodes_engine_base_nodes\ainodes_backend\k_sampler.py", line 71, in common_ksampler
    samples = sampler.sample(noise, positive_copy, negative_copy, cfg=cfg, latent_image=latent_image, start_step=start_step, last_step=last_step, force_full_denoise=force_full_denoise, denoise_mask=noise_mask, callback=callback, model_key=model_key)
  File "C:\Users\mix\ainodes\ainodes-engine\custom_nodes\ainodes_engine_base_nodes\ainodes_backend\samplers.py", line 624, in sample
    samples = getattr(k_diffusion_sampling, "sample_{}".format(self.sampler))(self.model_k, noise, sigmas, extra_args=extra_args, callback=callback)
  File "C:\Users\mix\ainodes\ainodes-engine\nodes_env\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "C:\Users\mix\ainodes\ainodes-engine\custom_nodes\ainodes_engine_base_nodes\ainodes_backend\k_diffusion\sampling.py", line 128, in sample_euler
    denoised = model(x, sigma_hat * s_in, **extra_args)
  File "C:\Users\mix\ainodes\ainodes-engine\nodes_env\lib\site-packages\torch\nn\modules\module.py", line 1502, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "C:\Users\mix\ainodes\ainodes-engine\nodes_env\lib\site-packages\torch\nn\modules\module.py", line 1511, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\mix\ainodes\ainodes-engine\custom_nodes\ainodes_engine_base_nodes\ainodes_backend\samplers.py", line 362, in forward
    out = self.inner_model(x, sigma, cond=cond, uncond=uncond, cond_scale=cond_scale, cond_concat=cond_concat, model_options=model_options)
  File "C:\Users\mix\ainodes\ainodes-engine\nodes_env\lib\site-packages\torch\nn\modules\module.py", line 1502, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "C:\Users\mix\ainodes\ainodes-engine\nodes_env\lib\site-packages\torch\nn\modules\module.py", line 1511, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\mix\ainodes\ainodes-engine\custom_nodes\ainodes_engine_base_nodes\ainodes_backend\k_diffusion\external.py", line 169, in forward
    return self.get_v(input * c_in, self.sigma_to_t(sigma), **kwargs) * c_out + input * c_skip
  File "C:\Users\mix\ainodes\ainodes-engine\custom_nodes\ainodes_engine_base_nodes\ainodes_backend\samplers.py", line 342, in get_v
    return self.inner_model.apply_model(x, t, cond, **kwargs)
  File "C:\Users\mix\ainodes\ainodes-engine\custom_nodes\ainodes_engine_base_nodes\ainodes_backend\samplers.py", line 351, in apply_model
    out = sampling_function(self.inner_model.apply_model, x, timestep, uncond, cond, cond_scale, cond_concat, model_options=model_options)
  File "C:\Users\mix\ainodes\ainodes-engine\custom_nodes\ainodes_engine_base_nodes\ainodes_backend\samplers.py", line 330, in sampling_function
    cond, uncond = calc_cond_uncond_batch(model_function, cond, uncond, x, timestep, max_total_area, cond_concat, model_options)
  File "C:\Users\mix\ainodes\ainodes-engine\custom_nodes\ainodes_engine_base_nodes\ainodes_backend\samplers.py", line 307, in calc_cond_uncond_batch
    output = model_function(input_x, timestep_, cond=c).chunk(batch_chunks)
  File "C:\Users\mix\ainodes\ainodes-engine\custom_nodes\ainodes_engine_base_nodes\ainodes_backend\sd_optimizations\sd_hijack_unet.py", line 71, in <lambda>
    setattr(resolved_obj, func_path[-1], lambda *args, **kwargs: self(*args, **kwargs))
  File "C:\Users\mix\ainodes\ainodes-engine\custom_nodes\ainodes_engine_base_nodes\ainodes_backend\sd_optimizations\sd_hijack_unet.py", line 82, in __call__
    return self.__orig_func(*args, **kwargs)
  File "C:\Users\mix\ainodes\ainodes-engine\ldm\models\diffusion\ddpm.py", line 859, in apply_model
    x_recon = self.model(x_noisy, t, **cond)
  File "C:\Users\mix\ainodes\ainodes-engine\nodes_env\lib\site-packages\torch\nn\modules\module.py", line 1502, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "C:\Users\mix\ainodes\ainodes-engine\nodes_env\lib\site-packages\torch\nn\modules\module.py", line 1511, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\mix\ainodes\ainodes-engine\ldm\models\diffusion\ddpm.py", line 1337, in forward
    out = self.diffusion_model(x, t, context=cc, control=control, transformer_options=transformer_options)
  File "C:\Users\mix\ainodes\ainodes-engine\nodes_env\lib\site-packages\torch\nn\modules\module.py", line 1502, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "C:\Users\mix\ainodes\ainodes-engine\nodes_env\lib\site-packages\torch\nn\modules\module.py", line 1511, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\mix\ainodes\ainodes-engine\ldm\modules\diffusionmodules\openaimodel.py", line 821, in forward
    h = forward_timestep_embed(module, h, emb, context, transformer_options)
  File "C:\Users\mix\ainodes\ainodes-engine\ldm\modules\diffusionmodules\openaimodel.py", line 97, in forward_timestep_embed
    x = layer(x, context, transformer_options)
  File "C:\Users\mix\ainodes\ainodes-engine\nodes_env\lib\site-packages\torch\nn\modules\module.py", line 1502, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "C:\Users\mix\ainodes\ainodes-engine\nodes_env\lib\site-packages\torch\nn\modules\module.py", line 1511, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\mix\ainodes\ainodes-engine\ldm\modules\attention.py", line 637, in forward
    x = block(x, context=context[i], transformer_options=transformer_options)
  File "C:\Users\mix\ainodes\ainodes-engine\nodes_env\lib\site-packages\torch\nn\modules\module.py", line 1502, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "C:\Users\mix\ainodes\ainodes-engine\nodes_env\lib\site-packages\torch\nn\modules\module.py", line 1511, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\mix\ainodes\ainodes-engine\ldm\modules\attention.py", line 526, in forward
    return checkpoint(self._forward, (x, context, transformer_options), self.parameters(), self.checkpoint)
  File "C:\Users\mix\ainodes\ainodes-engine\ldm\modules\diffusionmodules\util.py", line 121, in checkpoint
    return CheckpointFunction.apply(func, len(inputs), *args)
  File "C:\Users\mix\ainodes\ainodes-engine\nodes_env\lib\site-packages\torch\autograd\function.py", line 506, in apply
    return super().apply(*args, **kwargs)  # type: ignore[misc]
  File "C:\Users\mix\ainodes\ainodes-engine\ldm\modules\diffusionmodules\util.py", line 136, in forward
    output_tensors = ctx.run_function(*ctx.input_tensors)
  File "C:\Users\mix\ainodes\ainodes-engine\ldm\modules\attention.py", line 556, in _forward
    n = self.attn1(n, context=context_attn1, value=value_attn1)
  File "C:\Users\mix\ainodes\ainodes-engine\nodes_env\lib\site-packages\torch\nn\modules\module.py", line 1502, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "C:\Users\mix\ainodes\ainodes-engine\nodes_env\lib\site-packages\torch\nn\modules\module.py", line 1511, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\mix\ainodes\ainodes-engine\ldm\modules\attention.py", line 381, in forward
    sim = einsum('b i d, b j d -> b i j', q, k) * self.scale
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 18.91 GiB. GPU 0 has a total capacty of 23.99 GiB of which 727.41 MiB is free. Of the allocated memory 21.14 GiB is allocated by PyTorch, and 121.08 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

---End of Error---
Traceback (most recent call last):
  File "C:\Users\mix\ainodes\ainodes-engine\custom_nodes\ainodes_engine_base_nodes\torch_nodes\ksampler_node.py", line 184, in evalImplementation_thread
    x_sample = self.decode_sample(sample)
  File "C:\Users\mix\ainodes\ainodes-engine\custom_nodes\ainodes_engine_base_nodes\torch_nodes\ksampler_node.py", line 198, in decode_sample
    decoded = gs.models["vae"].decode(sample)
  File "C:\Users\mix\ainodes\ainodes-engine\custom_nodes\ainodes_engine_base_nodes\ainodes_backend\model_loader.py", line 404, in decode
    pixel_samples = self.first_stage_model.decode(1. / self.scale_factor * samples)
  File "C:\Users\mix\ainodes\ainodes-engine\ldm\models\autoencoder.py", line 94, in decode
    dec = self.decoder(z)
  File "C:\Users\mix\ainodes\ainodes-engine\nodes_env\lib\site-packages\torch\nn\modules\module.py", line 1502, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "C:\Users\mix\ainodes\ainodes-engine\nodes_env\lib\site-packages\torch\nn\modules\module.py", line 1511, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\mix\ainodes\ainodes-engine\ldm\modules\diffusionmodules\model.py", line 724, in forward
    h = self.up[i_level].block[i_block](h, temb)
  File "C:\Users\mix\ainodes\ainodes-engine\nodes_env\lib\site-packages\torch\nn\modules\module.py", line 1502, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "C:\Users\mix\ainodes\ainodes-engine\nodes_env\lib\site-packages\torch\nn\modules\module.py", line 1511, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\mix\ainodes\ainodes-engine\ldm\modules\diffusionmodules\model.py", line 133, in forward
    h = self.conv1(h)
  File "C:\Users\mix\ainodes\ainodes-engine\nodes_env\lib\site-packages\torch\nn\modules\module.py", line 1502, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "C:\Users\mix\ainodes\ainodes-engine\nodes_env\lib\site-packages\torch\nn\modules\module.py", line 1511, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\mix\ainodes\ainodes-engine\nodes_env\lib\site-packages\torch\nn\modules\conv.py", line 463, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "C:\Users\mix\ainodes\ainodes-engine\nodes_env\lib\site-packages\torch\nn\modules\conv.py", line 459, in _conv_forward
    return F.conv2d(input, weight, bias, self.stride,
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 704.00 MiB. GPU 0 has a total capacty of 23.99 GiB of which 0 bytes is free. Of the allocated memory 22.06 GiB is allocated by PyTorch, and 346.75 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

---End of Error---
Traceback (most recent call last):
  File "C:\Users\mix\ainodes\ainodes-engine\custom_nodes\ainodes_engine_base_nodes\torch_nodes\ksampler_node.py", line 184, in evalImplementation_thread
    x_sample = self.decode_sample(sample)
  File "C:\Users\mix\ainodes\ainodes-engine\custom_nodes\ainodes_engine_base_nodes\torch_nodes\ksampler_node.py", line 198, in decode_sample
    decoded = gs.models["vae"].decode_tiled(sample)
  File "C:\Users\mix\ainodes\ainodes-engine\custom_nodes\ainodes_engine_base_nodes\ainodes_backend\model_loader.py", line 422, in decode_tiled
    pixel_samples = self.first_stage_model.decode(1. / self.scale_factor * s_in.to(self.device))
  File "C:\Users\mix\ainodes\ainodes-engine\ldm\models\autoencoder.py", line 94, in decode
    dec = self.decoder(z)
  File "C:\Users\mix\ainodes\ainodes-engine\nodes_env\lib\site-packages\torch\nn\modules\module.py", line 1502, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "C:\Users\mix\ainodes\ainodes-engine\nodes_env\lib\site-packages\torch\nn\modules\module.py", line 1511, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\mix\ainodes\ainodes-engine\ldm\modules\diffusionmodules\model.py", line 724, in forward
    h = self.up[i_level].block[i_block](h, temb)
  File "C:\Users\mix\ainodes\ainodes-engine\nodes_env\lib\site-packages\torch\nn\modules\module.py", line 1502, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "C:\Users\mix\ainodes\ainodes-engine\nodes_env\lib\site-packages\torch\nn\modules\module.py", line 1511, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\mix\ainodes\ainodes-engine\ldm\modules\diffusionmodules\model.py", line 132, in forward
    h = self.swish(h)
  File "C:\Users\mix\ainodes\ainodes-engine\nodes_env\lib\site-packages\torch\nn\modules\module.py", line 1502, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "C:\Users\mix\ainodes\ainodes-engine\nodes_env\lib\site-packages\torch\nn\modules\module.py", line 1511, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\mix\ainodes\ainodes-engine\nodes_env\lib\site-packages\torch\nn\modules\activation.py", line 397, in forward
    return F.silu(input, inplace=self.inplace)
  File "C:\Users\mix\ainodes\ainodes-engine\nodes_env\lib\site-packages\torch\nn\functional.py", line 2076, in silu
    return torch._C._nn.silu_(input)
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 256.00 MiB. GPU 0 has a total capacty of 23.99 GiB of which 0 bytes is free. Of the allocated memory 22.66 GiB is allocated by PyTorch, and 267.06 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

---End of Error---
Timestamp: 2023-05-28 17:49:30
Traceback (most recent call last):
  File "C:\Users\mix\ainodes\ainodes-engine\custom_nodes\ainodes_engine_base_nodes\torch_nodes\ksampler_node.py", line 184, in evalImplementation_thread
    x_sample = self.decode_sample(sample)
  File "C:\Users\mix\ainodes\ainodes-engine\custom_nodes\ainodes_engine_base_nodes\torch_nodes\ksampler_node.py", line 198, in decode_sample
    decoded = gs.models["vae"].decode_tiled(sample)
  File "C:\Users\mix\ainodes\ainodes-engine\custom_nodes\ainodes_engine_base_nodes\ainodes_backend\model_loader.py", line 422, in decode_tiled
    pixel_samples = self.first_stage_model.decode(1. / self.scale_factor * s_in.to(self.device))
  File "C:\Users\mix\ainodes\ainodes-engine\ldm\models\autoencoder.py", line 94, in decode
    dec = self.decoder(z)
  File "C:\Users\mix\ainodes\ainodes-engine\nodes_env\lib\site-packages\torch\nn\modules\module.py", line 1502, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "C:\Users\mix\ainodes\ainodes-engine\nodes_env\lib\site-packages\torch\nn\modules\module.py", line 1511, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\mix\ainodes\ainodes-engine\ldm\modules\diffusionmodules\model.py", line 724, in forward
    h = self.up[i_level].block[i_block](h, temb)
  File "C:\Users\mix\ainodes\ainodes-engine\nodes_env\lib\site-packages\torch\nn\modules\module.py", line 1502, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "C:\Users\mix\ainodes\ainodes-engine\nodes_env\lib\site-packages\torch\nn\modules\module.py", line 1511, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\mix\ainodes\ainodes-engine\ldm\modules\diffusionmodules\model.py", line 132, in forward
    h = self.swish(h)
  File "C:\Users\mix\ainodes\ainodes-engine\nodes_env\lib\site-packages\torch\nn\modules\module.py", line 1502, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "C:\Users\mix\ainodes\ainodes-engine\nodes_env\lib\site-packages\torch\nn\modules\module.py", line 1511, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\mix\ainodes\ainodes-engine\nodes_env\lib\site-packages\torch\nn\modules\activation.py", line 397, in forward
    return F.silu(input, inplace=self.inplace)
  File "C:\Users\mix\ainodes\ainodes-engine\nodes_env\lib\site-packages\torch\nn\functional.py", line 2076, in silu
    return torch._C._nn.silu_(input)
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 256.00 MiB. GPU 0 has a total capacty of 23.99 GiB of which 0 bytes is free. Of the allocated memory 22.66 GiB is allocated by PyTorch, and 285.24 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

---End of Error---
Timestamp: 2023-05-28 17:52:17
Traceback (most recent call last):
  File "C:\Users\mix\ainodes\ainodes-engine\custom_nodes\ainodes_engine_base_nodes\torch_nodes\ksampler_node.py", line 184, in evalImplementation_thread
    x_sample = self.decode_sample(sample)
  File "C:\Users\mix\ainodes\ainodes-engine\custom_nodes\ainodes_engine_base_nodes\torch_nodes\ksampler_node.py", line 198, in decode_sample
    decoded = gs.models["vae"].decode_tiled(sample)
  File "C:\Users\mix\ainodes\ainodes-engine\custom_nodes\ainodes_engine_base_nodes\ainodes_backend\model_loader.py", line 422, in decode_tiled
    pixel_samples = self.first_stage_model.decode(1. / self.scale_factor * s_in.to(self.device))
  File "C:\Users\mix\ainodes\ainodes-engine\ldm\models\autoencoder.py", line 94, in decode
    dec = self.decoder(z)
  File "C:\Users\mix\ainodes\ainodes-engine\nodes_env\lib\site-packages\torch\nn\modules\module.py", line 1502, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "C:\Users\mix\ainodes\ainodes-engine\nodes_env\lib\site-packages\torch\nn\modules\module.py", line 1511, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\mix\ainodes\ainodes-engine\ldm\modules\diffusionmodules\model.py", line 724, in forward
    h = self.up[i_level].block[i_block](h, temb)
  File "C:\Users\mix\ainodes\ainodes-engine\nodes_env\lib\site-packages\torch\nn\modules\module.py", line 1502, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "C:\Users\mix\ainodes\ainodes-engine\nodes_env\lib\site-packages\torch\nn\modules\module.py", line 1511, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\mix\ainodes\ainodes-engine\ldm\modules\diffusionmodules\model.py", line 132, in forward
    h = self.swish(h)
  File "C:\Users\mix\ainodes\ainodes-engine\nodes_env\lib\site-packages\torch\nn\modules\module.py", line 1502, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "C:\Users\mix\ainodes\ainodes-engine\nodes_env\lib\site-packages\torch\nn\modules\module.py", line 1511, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\mix\ainodes\ainodes-engine\nodes_env\lib\site-packages\torch\nn\modules\activation.py", line 397, in forward
    return F.silu(input, inplace=self.inplace)
  File "C:\Users\mix\ainodes\ainodes-engine\nodes_env\lib\site-packages\torch\nn\functional.py", line 2076, in silu
    return torch._C._nn.silu_(input)
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 256.00 MiB. GPU 0 has a total capacty of 23.99 GiB of which 0 bytes is free. Of the allocated memory 22.66 GiB is allocated by PyTorch, and 285.24 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

---End of Error---
Traceback (most recent call last):
  File "C:\Users\mix\ainodes\ainodes-engine\custom_nodes\ainodes_engine_base_nodes\torch_nodes\ksampler_node.py", line 184, in evalImplementation_thread
    x_sample = self.decode_sample(sample)
  File "C:\Users\mix\ainodes\ainodes-engine\custom_nodes\ainodes_engine_base_nodes\torch_nodes\ksampler_node.py", line 198, in decode_sample
    decoded = gs.models["vae"].decode_tiled(sample)
  File "C:\Users\mix\ainodes\ainodes-engine\custom_nodes\ainodes_engine_base_nodes\ainodes_backend\model_loader.py", line 422, in decode_tiled
  File "C:\Users\mix\ainodes\ainodes-engine\ldm\models\autoencoder.py", line 94, in decode
    dec = self.decoder(z)
  File "C:\Users\mix\ainodes\ainodes-engine\nodes_env\lib\site-packages\torch\nn\modules\module.py", line 1502, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "C:\Users\mix\ainodes\ainodes-engine\nodes_env\lib\site-packages\torch\nn\modules\module.py", line 1511, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\mix\ainodes\ainodes-engine\ldm\modules\diffusionmodules\model.py", line 724, in forward
    h = self.up[i_level].block[i_block](h, temb)
  File "C:\Users\mix\ainodes\ainodes-engine\nodes_env\lib\site-packages\torch\nn\modules\module.py", line 1502, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "C:\Users\mix\ainodes\ainodes-engine\nodes_env\lib\site-packages\torch\nn\modules\module.py", line 1511, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\mix\ainodes\ainodes-engine\ldm\modules\diffusionmodules\model.py", line 132, in forward
    h = self.swish(h)
  File "C:\Users\mix\ainodes\ainodes-engine\nodes_env\lib\site-packages\torch\nn\modules\module.py", line 1502, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "C:\Users\mix\ainodes\ainodes-engine\nodes_env\lib\site-packages\torch\nn\modules\module.py", line 1511, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\mix\ainodes\ainodes-engine\nodes_env\lib\site-packages\torch\nn\modules\activation.py", line 397, in forward
    return F.silu(input, inplace=self.inplace)
  File "C:\Users\mix\ainodes\ainodes-engine\nodes_env\lib\site-packages\torch\nn\functional.py", line 2076, in silu
    return torch._C._nn.silu_(input)
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 256.00 MiB. GPU 0 has a total capacty of 23.99 GiB of which 0 bytes is free. Of the allocated memory 22.66 GiB is allocated by PyTorch, and 273.24 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

---End of Error---
Timestamp: 2023-05-28 17:54:15
Traceback (most recent call last):
  File "C:\Users\mix\ainodes\ainodes-engine\custom_nodes\ainodes_engine_base_nodes\torch_nodes\ksampler_node.py", line 184, in evalImplementation_thread
    x_sample = self.decode_sample(sample)
  File "C:\Users\mix\ainodes\ainodes-engine\custom_nodes\ainodes_engine_base_nodes\torch_nodes\ksampler_node.py", line 198, in decode_sample
    decoded = gs.models["vae"].decode_tiled(sample)
  File "C:\Users\mix\ainodes\ainodes-engine\custom_nodes\ainodes_engine_base_nodes\ainodes_backend\model_loader.py", line 424, in decode_tiled
    pixel_samples = self.first_stage_model.decode(1. / self.scale_factor * s_in.to(self.device))
  File "C:\Users\mix\ainodes\ainodes-engine\ldm\models\autoencoder.py", line 94, in decode
    dec = self.decoder(z)
  File "C:\Users\mix\ainodes\ainodes-engine\nodes_env\lib\site-packages\torch\nn\modules\module.py", line 1502, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "C:\Users\mix\ainodes\ainodes-engine\nodes_env\lib\site-packages\torch\nn\modules\module.py", line 1511, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\mix\ainodes\ainodes-engine\ldm\modules\diffusionmodules\model.py", line 724, in forward
    h = self.up[i_level].block[i_block](h, temb)
  File "C:\Users\mix\ainodes\ainodes-engine\nodes_env\lib\site-packages\torch\nn\modules\module.py", line 1502, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "C:\Users\mix\ainodes\ainodes-engine\nodes_env\lib\site-packages\torch\nn\modules\module.py", line 1511, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\mix\ainodes\ainodes-engine\ldm\modules\diffusionmodules\model.py", line 149, in forward
    return x+h
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 128.00 MiB. GPU 0 has a total capacty of 23.99 GiB of which 0 bytes is free. Of the allocated memory 22.53 GiB is allocated by PyTorch, and 429.38 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

---End of Error---
Timestamp: 2023-05-28 18:22:04
Traceback (most recent call last):
  File "C:\Users\mix\ainodes\ainodes-engine\ainodes_frontend\base\ai_node_base.py", line 205, in getOutput
    return self.values[object_name]
KeyError: '2630912419264_output_0'

---End of Error---
Timestamp: 2023-05-28 18:22:07
Traceback (most recent call last):
  File "C:\Users\mix\ainodes\ainodes-engine\ainodes_frontend\base\ai_node_base.py", line 205, in getOutput
    return self.values[object_name]
KeyError: '2630912419264_output_0'

---End of Error---
Traceback (most recent call last):
  File "C:\Users\mix\ainodes\ainodes-engine\ainodes_frontend\base\ai_node_base.py", line 205, in getOutput
    return self.values[object_name]
KeyError: '2630912418304_output_2'

---End of Error---
Timestamp: 2023-05-28 18:54:49
Traceback (most recent call last):
  File "C:\Users\mix\ainodes\ainodes-engine\custom_nodes\ainodes_engine_base_nodes\torch_nodes\conditioning_node.py", line 192, in evalImplementation_thread
    result = [self.get_conditioning(prompt=prompt)]
  File "C:\Users\mix\ainodes\ainodes-engine\custom_nodes\ainodes_engine_base_nodes\torch_nodes\conditioning_node.py", line 235, in get_conditioning
    c = clip.encode(prompt)
  File "C:\Users\mix\ainodes\ainodes-engine\custom_nodes\ainodes_engine_base_nodes\ainodes_backend\model_loader.py", line 524, in encode
    raise e
  File "C:\Users\mix\ainodes\ainodes-engine\custom_nodes\ainodes_engine_base_nodes\ainodes_backend\model_loader.py", line 520, in encode
    cond = self.cond_stage_model.encode_token_weights(tokens)
  File "C:\Users\mix\ainodes\ainodes-engine\custom_nodes\ainodes_engine_base_nodes\ainodes_backend\model_loader.py", line 539, in encode_token_weights
    z = self.encode(tokens)
  File "C:\Users\mix\ainodes\ainodes-engine\custom_nodes\ainodes_engine_base_nodes\ainodes_backend\model_loader.py", line 636, in encode
    return self(tokens)
  File "C:\Users\mix\ainodes\ainodes-engine\nodes_env\lib\site-packages\torch\nn\modules\module.py", line 1502, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "C:\Users\mix\ainodes\ainodes-engine\nodes_env\lib\site-packages\torch\nn\modules\module.py", line 1511, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\mix\ainodes\ainodes-engine\custom_nodes\ainodes_engine_base_nodes\ainodes_backend\model_loader.py", line 620, in forward
    tokens = self.set_up_textual_embeddings(tokens, backup_embeds)
  File "C:\Users\mix\ainodes\ainodes-engine\custom_nodes\ainodes_engine_base_nodes\ainodes_backend\model_loader.py", line 613, in set_up_textual_embeddings
    new_embedding.weight[n] = x
RuntimeError: The expanded size of the tensor (1024) must match the existing size (768) at non-singleton dimension 0.  Target sizes: [1024].  Tensor sizes: [768]

---End of Error---
